### PR TITLE
fixes NewRequest strips query from path parameter

### LINKED ISSUE #981: Beginning with 1.63.0, NewRequest strips query params, breaking some callers
This commit seems to be the culprit https://github.com/hashicorp/go-tfe/commit/417505b3914ee4e34a17d77b609b7f487bf4ceed#diff-2aefd6ea323a50ad81560708158f18e31d0d177f50aed3edd5a94353b7ab0f5aR292

### PR DESCRIPTION
**Pull request by brandonc**
Fixes a bug in `NewRequest` that did not allow query parameters to be specified in the first parameter, which broke several methods: `RegistryModules ReadVersion`, `VariableSets UpdateWorkspaces`, and `Workspaces Readme`

Closes #981

### CODE REVIEW

File: tfe.go [hunk 1]
```diff
@@ -310,6 +312,9 @@ func (c *Client) NewRequestWithAdditionalQueryParams(method, path string, reqBod
 		body = reqBody
 	}
 
+	for k, v := range u.Query() {
+		q[k] = v
+	}
```
Comment (sebasslash) [inline tfe.go:317]: :heart:

**Review by sebasslash — APPROVED** [review]
