### PR TITLE
Fixes project names being validated as IDs

### LINKED ISSUE #607: Project names can contain spaces, single quotes, etc and should not be validated as IDs
see related https://github.com/hashicorp/terraform-provider-tfe/issues/714

```
╷
│ Error: Error updating project prj-KFZ6GfAE7BLkESgk: invalid value for name
│
│   with tfe_project.foo,
│   on main.tf line 11, in resource "tfe_project" "foo":
│   11: resource "tfe_project" "foo" {
```

### PR DESCRIPTION
**Pull request by brandonc**
Closes #607

### CODE REVIEW

File: projects_integration_test.go [hunk 1]
```diff
@@ -123,7 +123,7 @@ func TestProjectsCreate(t *testing.T) {
 			Name: badIdentifier,
 		})
 		assert.Nil(t, w)
-		assert.EqualError(t, err, ErrInvalidName.Error())
+		assert.Contains(t, err.Error(), "invalid attribute\n\nName may only contain")
```
Comment (uturunku1) [inline projects_integration_test.go:126]: Is this sentence `Name may only contain` complete? or is it missing part of it, like `Name may only contain alphanumeric characters and underscore`?

**Review by uturunku1 — APPROVED** [review]

File: projects_integration_test.go (hunk 1 above)
Comment (brandonc) [reply projects_integration_test.go:126]: The error comes from the API, but I don't want to fully validate the response in case it ever evolves.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,7 +1,9 @@
-# Unreleased
+# v1.15.1
 
 ## Bug Fixes
 
+* Project names were being validated as ID's
```
[the remark this answers is not in the document]
Comment (brandonc) [reply CHANGELOG.md:5]: I'll link this PR

**Review by uturunku1 — APPROVED** [review]
